openapi: 3.2.0
info:
  description: The Chorus API is a REST API that enables you to retrieve information from and perform actions in Chorus.
  termsOfService: https://www.chorus.ai/terms
  title: Chorus Reports API
  version: 26.33.08
servers:
- url: /
- url: https://chorus.ai
security:
- basic: []
- bearer-token: []
- x-ziaccesstoken: []
tags:
- name: Reports
paths:
  /api/v1/reports/{id}/actions/export:
    post:
      deprecated: false
      description: This API is used to make an asynchronous call to generate a CSV file for the data of a given report. This CSV file will then be uploaded to Amazon S3, and an e-mail will be sent to the user containing a link to the file which will be valid for 7 days.
      operationId: post-api-v1-reports-id-actions-export
      parameters:
      - description: id
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            examples:
              All supported fields:
                value:
                  active_users_only: true
                  call_ids:
                  - 892A873532FB4F1090A62
                  end: '2026-08-13'
                  start: '2026-07-14'
                  teams:
                  - 123
                  - 456
              Minimum required fields:
                value:
                  start: '2026-07-14'
            schema:
              $ref: '#/components/schemas/ReportExportActionBody'
        required: true
      responses:
        '202':
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/TaskDoc'
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
      summary: Export the data of a report
      tags:
      - Reports
components:
  schemas:
    Error:
      properties:
        errors:
          items:
            properties:
              code:
                type:
                - string
                - 'null'
              detail:
                type:
                - string
                - 'null'
              id:
                type:
                - string
                - 'null'
              source:
                properties:
                  cookie:
                    type:
                    - string
                    - 'null'
                  header:
                    type:
                    - string
                    - 'null'
                  parameter:
                    type:
                    - string
                    - 'null'
                  path:
                    type:
                    - string
                    - 'null'
                  pointer:
                    type:
                    - string
                    - 'null'
                type:
                - object
                - 'null'
              status:
                type:
                - string
                - 'null'
              title:
                type:
                - string
                - 'null'
            type: object
          type: array
      required:
      - errors
      type: object
    Task:
      properties:
        attributes:
          properties:
            status:
              readOnly: true
              type: string
          required:
          - status
          type: object
        id:
          description: The unique ID of the task.
          example: '123'
          title: ID
          type: string
        type:
          description: The type of resource.
          enum:
          - task
          example: task
          title: Type
          type: string
      required:
      - attributes
      - type
      - id
      type: object
    ReportExportActionBody:
      properties:
        active_users_only:
          type:
          - boolean
          - 'null'
        call_ids:
          items:
            type: string
          type:
          - array
          - 'null'
        end:
          example: '2021-01-01T00:00:00Z'
          type:
          - string
          - 'null'
        start:
          example: '2021-01-01T00:00:00Z'
          type:
          - string
          - 'null'
        teams:
          items:
            type: integer
          type:
          - array
          - 'null'
      type: object
    TaskDoc:
      properties:
        data:
          $ref: '#/components/schemas/Task'
      required:
      - data
      type: object
  responses:
    BadRequest:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Bad request
    Conflict:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Conflict
  securitySchemes:
    basic:
      description: HTTP basic authentication (for those APIs that support it).
      scheme: basic
      type: http
    bearer-token:
      description: A Chorus token or a signed JWT.
      scheme: bearer
      type: http
    x-ziaccesstoken:
      description: A ZoomInfo access token.
      in: header
      name: x-ziaccesstoken
      type: apiKey
