openapi: 3.2.0
info:
  description: The Chorus API is a REST API that enables you to retrieve information from and perform actions in Chorus.
  termsOfService: https://www.chorus.ai/terms
  title: Chorus Video Conferences API
  version: 26.33.08
servers:
- url: /
- url: https://chorus.ai
security:
- basic: []
- bearer-token: []
- x-ziaccesstoken: []
tags:
- name: Video Conferences
paths:
  /api/v1/video_conferences:
    post:
      deprecated: false
      description: This API creates a new video conference.
      operationId: post-api-v1-video_conferences
      parameters: []
      requestBody:
        content:
          application/vnd.api+json:
            example:
              data:
                attributes:
                  provider: ZOOM
                type: video_conference
            schema:
              $ref: '#/components/schemas/VideoConferenceForCreateDoc'
        required: true
      responses:
        '201':
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/VideoConferenceDoc'
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
      summary: Create a new video conference
      tags:
      - Video Conferences
  /api/v1/video_conferences/{go_link}:
    delete:
      deprecated: false
      description: This API deletes the video conference with the given ID.
      operationId: delete-api-v1-video_conferences-go_link
      parameters:
      - description: go_link
        in: path
        name: go_link
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      summary: Delete a video conference
      tags:
      - Video Conferences
    patch:
      deprecated: false
      description: This API partially updates the video conference with the given ID.
      operationId: patch-api-v1-video_conferences-go_link
      parameters:
      - description: go_link
        in: path
        name: go_link
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/vnd.api+json:
            example:
              data:
                attributes:
                  duration: 30
                  start_time: '2022-01-30T18:00:00Z'
                  subject: Updated Meeting subject
                id: https://go.chorus.ai/8992359323
                type: video_conference
            schema:
              $ref: '#/components/schemas/VideoConferenceForPatchDoc'
        required: true
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      summary: Partially update a video conference
      tags:
      - Video Conferences
components:
  schemas:
    VideoConferenceForPatchDoc:
      properties:
        data:
          $ref: '#/components/schemas/VideoConferenceForPatch'
      required:
      - data
      type: object
    VideoConferenceForCreateDoc:
      properties:
        data:
          $ref: '#/components/schemas/VideoConferenceForCreate'
      required:
      - data
      type: object
    VideoConferenceForCreate:
      properties:
        attributes:
          properties:
            provider:
              enum:
              - 8X8
              - GOOGLE_MEET
              - MSTEAMS
              - WEBEX
              - ZOOM
              example: 8X8
              type: string
          required:
          - provider
          type: object
        type:
          description: The type of resource.
          enum:
          - video_conference
          example: video_conference
          title: Type
          type: string
      required:
      - attributes
      - type
      type: object
    Error:
      properties:
        errors:
          items:
            properties:
              code:
                type:
                - string
                - 'null'
              detail:
                type:
                - string
                - 'null'
              id:
                type:
                - string
                - 'null'
              source:
                properties:
                  cookie:
                    type:
                    - string
                    - 'null'
                  header:
                    type:
                    - string
                    - 'null'
                  parameter:
                    type:
                    - string
                    - 'null'
                  path:
                    type:
                    - string
                    - 'null'
                  pointer:
                    type:
                    - string
                    - 'null'
                type:
                - object
                - 'null'
              status:
                type:
                - string
                - 'null'
              title:
                type:
                - string
                - 'null'
            type: object
          type: array
      required:
      - errors
      type: object
    VideoConferenceDoc:
      properties:
        data:
          $ref: '#/components/schemas/VideoConference'
      required:
      - data
      type: object
    VideoConference:
      properties:
        attributes:
          properties:
            provider:
              enum:
              - 8X8
              - GOOGLE_MEET
              - MSTEAMS
              - WEBEX
              - ZOOM
              example: 8X8
              type: string
          required:
          - provider
          type: object
        id:
          description: The unique ID of the video conference.
          example: '123'
          title: ID
          type: string
        type:
          description: The type of resource.
          enum:
          - video_conference
          example: video_conference
          title: Type
          type: string
      required:
      - attributes
      - type
      - id
      type: object
    VideoConferenceForPatch:
      properties:
        attributes:
          properties:
            duration:
              type: integer
            start_time:
              example: '2021-01-01T00:00:00+00:00'
              format: date-time
              type: string
            subject:
              type:
              - string
              - 'null'
          required:
          - duration
          - start_time
          type: object
        id:
          description: The unique ID of the video conference.
          example: '123'
          title: ID
          type: string
        type:
          description: The type of resource.
          enum:
          - video_conference
          example: video_conference
          title: Type
          type: string
      required:
      - attributes
      - type
      - id
      type: object
  responses:
    BadRequest:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Bad request
    NotFound:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Not found
    Conflict:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Conflict
  securitySchemes:
    basic:
      description: HTTP basic authentication (for those APIs that support it).
      scheme: basic
      type: http
    bearer-token:
      description: A Chorus token or a signed JWT.
      scheme: bearer
      type: http
    x-ziaccesstoken:
      description: A ZoomInfo access token.
      in: header
      name: x-ziaccesstoken
      type: apiKey
