openapi: 3.2.0
info:
  description: The Chorus API is a REST API that enables you to retrieve information from and perform actions in Chorus.
  termsOfService: https://www.chorus.ai/terms
  title: Chorus Integrations Calendar API
  version: 26.33.08
servers:
- url: /
- url: https://chorus.ai
security:
- basic: []
- bearer-token: []
- x-ziaccesstoken: []
tags:
- name: Integrations Calendar
paths:
  /api/v1/integrations/google_calendar/actions/connect:
    get:
      deprecated: false
      description: This API is used to "connect" the customer to Google Calendar service account
      operationId: get-api-v1-integrations-google_calendar-actions-connect
      parameters: []
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
      summary: Connect Google Calendar service account
      tags:
      - Integrations Calendar
  /api/v1/integrations/google_calendar/actions/verify:
    post:
      deprecated: false
      description: 'This API is used to verify an email service account.

        - At least two "accessible" emails must be provided.

        - A `204 No Content` will be returned if the verification is successful and a `400 Bad Request` will be returned, along withrelevant details, if it is not.'
      operationId: post-api-v1-integrations-google_calendar-actions-verify
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              emails:
              - john.smith@acme.com
              - bill.jones@acme.com
            schema:
              $ref: '#/components/schemas/VerifyCalendarServiceAccount'
        required: true
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
      summary: Verify calendar service account
      tags:
      - Integrations Calendar
  /api/v1/integrations/office365_calendar/actions/connect:
    get:
      deprecated: false
      description: This API is used to "connect" the customer to Office365 Calendar service account
      operationId: get-api-v1-integrations-office365_calendar-actions-connect
      parameters: []
      responses:
        '302':
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
      summary: Connect Office365 Calendar service account
      tags:
      - Integrations Calendar
  /api/v1/integrations/office365_calendar/actions/verify:
    post:
      deprecated: false
      description: 'This API is used to verify an email service account.

        - At least two "accessible" emails must be provided.

        - A `204 No Content` will be returned if the verification is successful and a `400 Bad Request` will be returned, along withrelevant details, if it is not.'
      operationId: post-api-v1-integrations-office365_calendar-actions-verify
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              emails:
              - john.smith@acme.com
              - bill.jones@acme.com
            schema:
              $ref: '#/components/schemas/VerifyCalendarServiceAccount'
        required: true
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
      summary: Verify calendar service account
      tags:
      - Integrations Calendar
components:
  schemas:
    Error:
      properties:
        errors:
          items:
            properties:
              code:
                type:
                - string
                - 'null'
              detail:
                type:
                - string
                - 'null'
              id:
                type:
                - string
                - 'null'
              source:
                properties:
                  cookie:
                    type:
                    - string
                    - 'null'
                  header:
                    type:
                    - string
                    - 'null'
                  parameter:
                    type:
                    - string
                    - 'null'
                  path:
                    type:
                    - string
                    - 'null'
                  pointer:
                    type:
                    - string
                    - 'null'
                type:
                - object
                - 'null'
              status:
                type:
                - string
                - 'null'
              title:
                type:
                - string
                - 'null'
            type: object
          type: array
      required:
      - errors
      type: object
    VerifyCalendarServiceAccount:
      properties:
        emails:
          items:
            type: string
          type: array
      required:
      - emails
      type: object
  responses:
    Conflict:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Conflict
    BadRequest:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Bad request
  securitySchemes:
    basic:
      description: HTTP basic authentication (for those APIs that support it).
      scheme: basic
      type: http
    bearer-token:
      description: A Chorus token or a signed JWT.
      scheme: bearer
      type: http
    x-ziaccesstoken:
      description: A ZoomInfo access token.
      in: header
      name: x-ziaccesstoken
      type: apiKey
