openapi: 3.2.0
info:
  description: The Chorus API is a REST API that enables you to retrieve information from and perform actions in Chorus.
  termsOfService: https://www.chorus.ai/terms
  title: Chorus Public Playlist Moments API
  version: 26.33.08
servers:
- url: /
- url: https://chorus.ai
security:
- basic: []
- bearer-token: []
- x-ziaccesstoken: []
tags:
- name: Public Playlist Moments
paths:
  /api/v1/playlists/moments:
    post:
      deprecated: false
      description: This API creates a new playlist.
      operationId: post-api-v1-playlists-moments
      parameters: []
      requestBody:
        content:
          application/vnd.api+json:
            example:
              data:
                attributes:
                  callid: call_id_12345
                  description: new moment
                  moment_duration: 7
                  moment_time: 0.0
                  playlist: 12345
                type: playlist_moment_request
            schema:
              $ref: '#/components/schemas/PlaylistMomentRequestForCreateDoc'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
      summary: Add a new playlist moment
      tags:
      - Public Playlist Moments
  /api/v1/playlists/moments/{id}:
    patch:
      deprecated: false
      description: This API partially updates the playlist moment with the given ID.
      operationId: patch-api-v1-playlists-moments-id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/vnd.api+json:
            example:
              data:
                attributes:
                  description: New description for existing playlist moment
                id: '11111'
                type: playlist_moment
            schema:
              $ref: '#/components/schemas/MomentForPatchDoc'
        required: true
      responses:
        '200':
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/PlaylistMomentDoc'
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      summary: Partially update a playlist moment
      tags:
      - Public Playlist Moments
components:
  schemas:
    MomentForPatchDoc:
      properties:
        data:
          $ref: '#/components/schemas/MomentForPatch'
      required:
      - data
      type: object
    MomentForPatch:
      properties:
        attributes:
          properties:
            description:
              type:
              - string
              - 'null'
            playlist:
              type:
              - integer
              - 'null'
          type: object
        id:
          description: The unique ID of the playlist moment.
          example: '123'
          title: ID
          type: string
        type:
          description: The type of resource.
          enum:
          - playlist_moment
          example: playlist_moment
          title: Type
          type: string
      required:
      - attributes
      - type
      - id
      type: object
    PlaylistMomentDoc:
      properties:
        data:
          $ref: '#/components/schemas/PlaylistMoment'
      required:
      - data
      type: object
    Error:
      properties:
        errors:
          items:
            properties:
              code:
                type:
                - string
                - 'null'
              detail:
                type:
                - string
                - 'null'
              id:
                type:
                - string
                - 'null'
              source:
                properties:
                  cookie:
                    type:
                    - string
                    - 'null'
                  header:
                    type:
                    - string
                    - 'null'
                  parameter:
                    type:
                    - string
                    - 'null'
                  path:
                    type:
                    - string
                    - 'null'
                  pointer:
                    type:
                    - string
                    - 'null'
                type:
                - object
                - 'null'
              status:
                type:
                - string
                - 'null'
              title:
                type:
                - string
                - 'null'
            type: object
          type: array
      required:
      - errors
      type: object
    PlaylistMomentRequestForCreate:
      properties:
        attributes:
          properties:
            callid:
              type: string
            description:
              type:
              - string
              - 'null'
            moment_duration:
              type: number
            moment_time:
              type:
              - number
              - 'null'
            playlist:
              type: integer
          required:
          - callid
          - moment_duration
          - playlist
          type: object
        type:
          description: The type of resource.
          enum:
          - playlist_moment_request
          example: playlist_moment_request
          title: Type
          type: string
      required:
      - attributes
      - type
      type: object
    PlaylistMoment:
      properties:
        attributes:
          properties:
            _created_at:
              example: '2021-01-01T00:00:00Z'
              readOnly: true
              type: string
            _created_by:
              readOnly: true
              type: integer
            account:
              properties:
                id:
                  type: integer
                name:
                  type: string
              required:
              - id
              - name
              type: object
            call_id:
              type: string
            date_time:
              example: '2021-01-01T00:00:00Z'
              type: string
            description:
              type: string
            meta:
              properties:
                is_new:
                  type: boolean
                was_played:
                  type: boolean
              required:
              - is_new
              - was_played
              type: object
            moment_duration:
              type: integer
            recording:
              properties:
                duration:
                  type: number
                owner:
                  type: integer
              required:
              - duration
              - owner
              type: object
            snippet_time:
              type: integer
            subject:
              type: string
            user_name:
              type: string
          required:
          - account
          - call_id
          - _created_by
          - _created_at
          - date_time
          - description
          - meta
          - moment_duration
          - recording
          - snippet_time
          - subject
          - user_name
          type: object
        id:
          description: The unique ID of the playlist moment.
          example: '123'
          title: ID
          type: string
        type:
          description: The type of resource.
          enum:
          - playlist_moment
          example: playlist_moment
          title: Type
          type: string
      required:
      - attributes
      - type
      - id
      type: object
    PlaylistMomentRequestForCreateDoc:
      properties:
        data:
          $ref: '#/components/schemas/PlaylistMomentRequestForCreate'
      required:
      - data
      type: object
  responses:
    BadRequest:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Bad request
    NotFound:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Not found
    Conflict:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Conflict
  securitySchemes:
    basic:
      description: HTTP basic authentication (for those APIs that support it).
      scheme: basic
      type: http
    bearer-token:
      description: A Chorus token or a signed JWT.
      scheme: bearer
      type: http
    x-ziaccesstoken:
      description: A ZoomInfo access token.
      in: header
      name: x-ziaccesstoken
      type: apiKey
