openapi: 3.2.0
info:
  description: "The Chorus API is a REST API that enables you to retrieve information from and perform actions in Chorus. The Chorus API supports the following use cases:\n\n1. Retrieve data about your users in Chorus\n2. Retrieve data about your engagements (meetings and dialer calls)\n3. Upload new recordings into Chorus\n4. Delete recordings from Chorus\n\n# Authentication\nThe Chorus API uses API tokens to authenticate requests. API tokens can be generated for each Chorus user, and is managed via the Personal Settings page within the Chorus application. For users to be able to create API token(s), their role as defined in Chorus must be permitted access to the Chorus API via roles & permissions settings. \nAuthentication is performed using the Authorization header, as in the the following example:\n\n```\ncurl -H \"Authorization:abcdefghijklmnopqrstuvwxyz0123456789\" https://chorus.ai/v3/engagements\n```\n\nAn API token must be associated with a registered user in Chorus to ensure control over data access and permissions, and to ensure traceability. During the early access period, please contact your Chorus customer success manager to obtain your personal API token.\n\n# Privacy and Data Access Control\n\nThe following controls apply when retrieving data or performing an action via the Chorus API.\n\n1. Recordings marked as private are not returned in API response. \n2. If enabled, data access control settings configured for the access key user applies to access via API. This means that in order to retrieve data on all recordings within Chorus, the users associated with the API token must also have access to all recordings.\n3. Permissions on actions a user may perform within the Chorus application as specified in roles & permissions settings also apply to actions performed via API."
  termsOfService: https://www.chorus.ai/terms
  title: Chorus Public External Moments API
  version: 26.33.08
servers:
- url: /
- url: https://chorus.ai
security:
- basic: []
- bearer-token: []
- x-ziaccesstoken: []
tags:
- name: Public External Moments
paths:
  /api/v1/moments:
    post:
      deprecated: false
      description: This API creates a new moment.
      operationId: post-api-v1-moments
      parameters: []
      requestBody:
        content:
          application/vnd.api+json:
            example:
              data:
                attributes:
                  callid: call_id_12345
                  moment_duration: 7
                  moment_time: 0.0
                  note: ''
                  subject: ''
                  url_string: ''
                type: moment_create_request
            schema:
              $ref: '#/components/schemas/MomentCreateRequestForCreateDoc'
        required: true
      responses:
        '201':
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/MomentDoc'
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
      summary: Add a new moment
      tags:
      - Public External Moments
  /api/v1/moments/{id}:
    put:
      deprecated: false
      description: Updates a moment with the specified ID.
      operationId: put-api-v1-moments-id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/vnd.api+json:
            example:
              data:
                attributes:
                  moment_time: 3.0
                  note: ''
                  subject: ''
                  url_string: ''
                id: '11111'
                type: moment_edit_request
            schema:
              $ref: '#/components/schemas/MomentEditRequestDoc'
        required: true
      responses:
        '200':
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/MomentDoc'
          description: Success
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      summary: Updates a moment by ID.
      tags:
      - Public External Moments
components:
  responses:
    BadRequest:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Bad request
    Conflict:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Conflict
    NotFound:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Not found
  schemas:
    MomentDoc:
      properties:
        data:
          $ref: '#/components/schemas/Moment'
      required:
      - data
      type: object
    Moment:
      properties:
        attributes:
          properties:
            account:
              properties:
                id:
                  type:
                  - string
                  - 'null'
                name:
                  type:
                  - string
                  - 'null'
              type:
              - object
              - 'null'
            asr:
              type:
              - string
              - 'null'
            conversation:
              type:
              - string
              - 'null'
            creator:
              properties:
                company:
                  type:
                  - string
                  - 'null'
                id:
                  type:
                  - string
                  - 'null'
                name:
                  type:
                  - string
                  - 'null'
                picture:
                  type:
                  - string
                  - 'null'
              type:
              - object
              - 'null'
            duration:
              type:
              - number
              - 'null'
            expiration_date:
              example: '2021-01-01T00:00:00Z'
              type:
              - string
              - 'null'
            internal_only:
              default: false
              type:
              - boolean
              - 'null'
            link:
              type:
              - string
              - 'null'
            logo:
              type:
              - string
              - 'null'
            logo_bg:
              type:
              - string
              - 'null'
            note:
              type:
              - string
              - 'null'
            opportunity:
              properties:
                amount:
                  type:
                  - number
                  - 'null'
                close_date:
                  example: '2021-01-01T00:00:00Z'
                  type:
                  - string
                  - 'null'
                id:
                  type:
                  - string
                  - 'null'
                initial_amount:
                  type:
                  - number
                  - 'null'
                name:
                  type:
                  - string
                  - 'null'
                on_stage_since:
                  example: '2021-01-01T00:00:00Z'
                  type:
                  - string
                  - 'null'
                owner_name:
                  type:
                  - string
                  - 'null'
                stage:
                  type:
                  - string
                  - 'null'
              type:
              - object
              - 'null'
            password:
              type:
              - string
              - 'null'
            read_receipts:
              default: false
              type:
              - boolean
              - 'null'
            recording_duration:
              type:
              - number
              - 'null'
            share_email_address_required:
              default: true
              type:
              - boolean
              - 'null'
            shared_on:
              example: '2021-01-01T00:00:00Z'
              type:
              - string
              - 'null'
            speaker:
              properties:
                email:
                  type:
                  - string
                  - 'null'
                id:
                  type:
                  - string
                  - 'null'
                name:
                  type:
                  - string
                  - 'null'
                type:
                  type:
                  - string
                  - 'null'
              type:
              - object
              - 'null'
            start:
              type:
              - number
              - 'null'
            start_time:
              example: '2021-01-01T00:00:00Z'
              type:
              - string
              - 'null'
            subject:
              type:
              - string
              - 'null'
            thumbnail_link:
              type:
              - string
              - 'null'
            time:
              example: '2021-01-01T00:00:00Z'
              type:
              - string
              - 'null'
            url_string:
              type:
              - string
              - 'null'
            user:
              properties:
                email:
                  type:
                  - string
                  - 'null'
                id:
                  type:
                  - string
                  - 'null'
                name:
                  type:
                  - string
                  - 'null'
                picture:
                  type:
                  - string
                  - 'null'
              type:
              - object
              - 'null'
            video_link:
              type:
              - string
              - 'null'
            video_upload_time:
              example: '2021-01-01T00:00:00Z'
              type:
              - string
              - 'null'
          type: object
        id:
          description: The unique ID of the moment.
          example: '123'
          title: ID
          type: string
        type:
          description: The type of resource.
          enum:
          - moment
          example: moment
          title: Type
          type: string
      required:
      - attributes
      - type
      - id
      type: object
    MomentCreateRequestForCreateDoc:
      properties:
        data:
          $ref: '#/components/schemas/MomentCreateRequestForCreate'
      required:
      - data
      type: object
    MomentEditRequest:
      properties:
        attributes:
          properties:
            expiration_date:
              example: '2021-01-01T00:00:00Z'
              type:
              - string
              - 'null'
            moment_duration:
              type:
              - number
              - 'null'
            moment_time:
              type:
              - number
              - 'null'
            note:
              default: ''
              type:
              - string
              - 'null'
            password:
              type:
              - string
              - 'null'
            subject:
              default: ''
              type:
              - string
              - 'null'
            url_string:
              default: ''
              type:
              - string
              - 'null'
          type: object
        id:
          description: The unique ID of the moment edit request.
          example: '123'
          title: ID
          type: string
        type:
          description: The type of resource.
          enum:
          - moment_edit_request
          example: moment_edit_request
          title: Type
          type: string
      required:
      - attributes
      - type
      - id
      type: object
    Error:
      properties:
        errors:
          items:
            properties:
              code:
                type:
                - string
                - 'null'
              detail:
                type:
                - string
                - 'null'
              id:
                type:
                - string
                - 'null'
              source:
                properties:
                  cookie:
                    type:
                    - string
                    - 'null'
                  header:
                    type:
                    - string
                    - 'null'
                  parameter:
                    type:
                    - string
                    - 'null'
                  path:
                    type:
                    - string
                    - 'null'
                  pointer:
                    type:
                    - string
                    - 'null'
                type:
                - object
                - 'null'
              status:
                type:
                - string
                - 'null'
              title:
                type:
                - string
                - 'null'
            type: object
          type: array
      required:
      - errors
      type: object
    MomentEditRequestDoc:
      properties:
        data:
          $ref: '#/components/schemas/MomentEditRequest'
      required:
      - data
      type: object
    MomentCreateRequestForCreate:
      properties:
        attributes:
          properties:
            callid:
              type: string
            expiration_date:
              example: '2021-01-01T00:00:00Z'
              type:
              - string
              - 'null'
            moment_duration:
              type: number
            moment_time:
              type: number
            note:
              default: ''
              type:
              - string
              - 'null'
            password:
              type:
              - string
              - 'null'
            subject:
              default: ''
              type:
              - string
              - 'null'
            url_string:
              default: ''
              type:
              - string
              - 'null'
          required:
          - callid
          - moment_time
          - moment_duration
          type: object
        type:
          description: The type of resource.
          enum:
          - moment_create_request
          example: moment_create_request
          title: Type
          type: string
      required:
      - attributes
      - type
      type: object
  securitySchemes:
    basic:
      description: HTTP basic authentication (for those APIs that support it).
      scheme: basic
      type: http
    bearer-token:
      description: A Chorus token or a signed JWT.
      scheme: bearer
      type: http
    x-ziaccesstoken:
      description: A ZoomInfo access token.
      in: header
      name: x-ziaccesstoken
      type: apiKey
